include:

- project: nci-gdc/gitlab-templates
  ref: master
  file:
  - templates/global/full.yaml

variables:
  DOCKER_VERSION: "27.4.0"

build_dockers:
  stage: build
  services:
  - docker:${DOCKER_VERSION}-dind
  tags:
  - dind
  image: docker:${DOCKER_VERSION}-dind
  before_script:
  - docker info
  - apk add --no-cache bash moreutils git go curl just
  variables:
    BASE_CONTAINER_REGISTRY: "docker.osdc.io"
  script:
  - just docker-build
