[tox]
envlist = py311,help,version,ruff,type,cov
isolated_build = true


[tox:.package]
basepython = python3.11


[testenv]
basepython = python3.11
setenv =
    package = fastqc_to_json
    PYTHONHASHSEED = 0
passenv =
    PIP_EXTRA_INDEX_URL
skip_install = false
install_command = python -m pip install {opts} {packages}
extras = test
commands =
    pytest -vv {posargs}


[testenv:dev]
basepython = python3.11
extras =
    dev
    test


[testenv:detect-secrets]
basepython = python3.11
deps =
    detect-secrets==1.5.0
skip_install = true
commands =
    detect-secrets scan > .secrets.baseline


[testenv:compile]
basepython = python3.11
deps =
    uv
skip_install = true
commands =
    uv pip compile -o requirements.txt pyproject.toml


[testenv:help]
basepython = python3.11
skip_install = false
commands =
    python -m {env:package} --help


[testenv:cov]
basepython = python3.11
extras = test
commands =
    coverage run -m pytest tests/
    coverage combine
    coverage report -m
    coverage xml
    coverage xml -o test-reports/results.xml


[testenv:ruff]
basepython = python3.11
skip_install = false
deps =
    ruff
commands =
    ruff check {env:package}/ tests/


[testenv:type]
basepython = python3.11
skip_install = false
deps =
    mypy
extras =
    type
commands =
    mypy {env:package}/


[testenv:build]
basepython = python3.11
skip_install = false
isolated_build = false
extras =
    build
commands =
    python -m setuptools_scm
    python -m flit build


[testenv:publish]
basepython = python3.11
isolated_build = false
allowlist_externals =
    just
skip_install = false
passenv =
    TWINE_USERNAME
    TWINE_PASSWORD
    TWINE_REPOSITORY_URL
extras =
    build
commands =
    python -m setuptools_scm
    python -m flit build
    twine check dist/*
    twine upload dist/*


[testenv:version]
basepython = python3.11
skip_install = true
allowlist_externals =
    git
commands =
    git describe --tags --always


[testenv:cruft]
basepython = python3.11
skip_install = true
deps =
    cruft
allowlist_externals =
    git
commands =
    cruft check
